# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: ghc-7.10.2

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- aeson-0.10.0.0
- aeson-extra-0.2.2.0
- aeson-pretty-0.7.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- asn1-encoding-0.9.3
- asn1-parse-0.9.4
- asn1-types-0.3.1
- async-2.0.2
- attoparsec-0.13.0.1
- authenticate-1.3.2.11
- auto-update-0.1.2.2
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- blaze-textual-0.2.1.0
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.6.0.0
- case-insensitive-1.2.0.5
- cereal-0.4.1.1
- cipher-aes-0.2.11
- clientsession-0.9.1.1
- cmdargs-0.10.13
- conduit-1.2.5.1
- conduit-extra-1.1.9.1
- connection-0.2.5
- cookie-0.4.1.6
- cprng-aes-0.6.1
- crypto-api-0.13.2
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- cryptohash-0.11.6
- cryptohash-conduit-0.1.1
- cryptonite-0.8
- css-text-0.1.2.1
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dlist-0.7.1.2
- easy-file-0.2.1
- email-validate-2.1.3
- enclosed-exceptions-1.0.1.1
- entropy-0.3.7
- exceptions-0.8.0.2
- fast-logger-2.4.1
- file-embed-0.0.9
- hashable-1.2.3.3
- hex-0.1.2
- hjsmin-0.1.5.1
- hourglass-0.2.9
- http-api-data-0.2.1
- http-client-0.4.24
- http-client-tls-0.2.2
- http-conduit-2.1.8
- http-date-0.0.6.1
- http-types-0.9
- http2-1.2.0
- iproute-1.7.0
- language-javascript-0.5.14.2
- lifted-base-0.2.3.6
- memory-0.10
- mime-mail-0.4.11
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- monad-logger-0.3.15
- monad-loops-0.4.3
- mtl-2.2.1
- mwc-random-0.13.3.2
- mysql-0.1.1.8
- mysql-simple-0.2.2.5
- network-2.6.2.1
- network-uri-2.6.0.3
- nonce-1.0.2
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.12.0.0
- parsec-3.1.9
- path-pieces-0.2.1
- pcre-light-0.4.0.4
- pem-0.2.2
- persistent-2.2.2
- persistent-mysql-2.2
- persistent-template-2.1.4
- primitive-0.6.1.0
- psqueues-0.2.0.3
- random-1.1
- resource-pool-0.2.3.2
- resourcet-1.1.6
- safe-0.3.9
- scientific-0.3.4.2
- securemem-0.1.9
- semigroups-0.18.0.1
- setenv-0.1.1.3
- shakespeare-2.0.7
- silently-1.2.5
- simple-sendfile-0.2.21
- skein-1.0.9.3
- socks-0.5.4
- stm-2.4.4
- stm-chans-3.0.0.4
- streaming-commons-0.1.14.2
- stringsearch-0.3.6.6
- syb-0.6
- tagged-0.8.2
- tagsoup-0.13.5
- tagstream-conduit-0.5.5.3
- text-1.2.1.3
- tls-1.3.3
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unix-time-0.3.6
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- vault-0.3.0.4
- vector-0.11.0.0
- void-0.7.1
- wai-3.0.4.0
- wai-app-static-3.1.2
- wai-extra-3.0.12
- wai-logger-2.2.4.1
- warp-3.1.8
- word8-0.1.2
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.1
- x509-validation-1.6.3
- xml-conduit-1.3.2
- xml-types-0.3.6
- xss-sanitize-0.3.5.6
- yaml-0.8.15.1
- yesod-1.4.2
- yesod-auth-1.4.8
- yesod-core-1.4.15.1
- yesod-form-1.4.5
- yesod-persistent-1.4.0.3
- yesod-static-1.5.0.3
- zlib-0.6.1.1

# Override default flag values for local packages and extra-deps
flags:
  text:
    integer-simple: false

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
